spring:
  redis:
    host: local.redis.com
    port: 6379
    password:
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop_auth?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: shopUser
    password: shopUserPwd@
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  rabbitmq:
    host: local.rabbitmq.com
    port: 5672
    username: cloud-dev
    password: cloud-dev
    virtual-host: /
  mvc:
    servlet:
      load-on-startup: 1
    view:
      prefix: classpath:/templates/
      suffix: .html
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web

#mybatis相关配置
mybatis:
  type-aliases-package: com.shop.oauth
  mapper-locations: classpath:/mybatis-mapper/*
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

security:
  oauth2:
    resource:
      user-info-uri: http://local.gateway.com:8092/user-me
      prefer-token-info: false

access_token:
  store-jwt: false
  jwt-signing-key: xiao@wei@jia@gou=$==+_+%0%:)(:)
  add-userinfo: false
logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log
ribbon:
  eager-load:
    enabled: true
    clients: userinfo-center
  ReadTimeout: 100000
  ConnectTimeout: 100000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


